def file_handling(f, time_elapsed, memory, score, m_perc, mm_perc, gaps_perc):
    f.write('\n')
    f.write('New alignment status')
    f.write('\n')
    f.write('Time needed in seconds: ' + str(time_elapsed) + ' and memory used in Mbs: ' + str(memory))
    f.write('\n')
    f.write('Final Score:' + str(score))
    f.write('\n')
    f.write('Matches: ' + str(m_perc) + '%')
    f.write('\n')
    f.write('Mismatches: ' + str(mm_perc) + '%')
    f.write('\n')
    f.write('Gaps: ' + str(gaps_perc) + '%')
    f.write('\n')
    f.write('End of alignment')
    f.write('\n')
